# Generated by Django 5.2.7 on 2025-10-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0003_alter_location_latitude_alter_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
