# Generated by Django 5.2.7 on 2025-10-26 03:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0005_geofence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeofenceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_inside', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_known_geofence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker_app.geofence')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geofence_status', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
